# Generated by Django 2.2 on 2022-01-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
